# Generated by Django 3.2.13 on 2022-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='designation',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='district',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='station',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='login',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missingdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
