# Generated by Django 3.0.5 on 2022-09-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0002_auto_20220927_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='login',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missingdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
